import { useState } from "react";
import DashboardLayout from "../components/DashboardLayout";

export default function BeforeAfter() {
  const [sliderPosition, setSliderPosition] = useState(50);
  const [isModalOpen, setIsModalOpen] = useState(false);

  // High-fidelity production mock data mirroring a real live Llama 4 Vision breakdown
  const projectDetails = {
    title: "Modern Living Room Makeover",
    style: "Scandinavian Minimalist",
    date: "July 2026",
    analysis: {
      overview: "Comprehensive architectural optimization transforming a constrained, dark layout into an airy, light-filled modern Scandinavian habitat.",
      palette: ["#F3F4F6 (Matt Off-White)", "#E5E7EB (Soft Ash Gray)", "#1E1B4B (Deep Indigo Accent)", "#D4A373 (Natural Light Oak)"],
      recommendations: [
        "Replaced bulky dark sofa seating with a low-profile premium L-shaped sectional to open peripheral floor pathways.",
        "Integrated a 42-inch custom geometric ash-wood wall clock to anchor the primary vertical sightline surface.",
        "Introduced ceiling-height sheer linen drapery panels to maximize natural window light diffusion.",
        "Positioned custom modular oak shelving units to hide clutter while adding organic accent greenery."
      ]
    }
  };

  return (
    <DashboardLayout>
      <div className="max-w-5xl mx-auto p-2 tracking-wide font-sans text-slate-900 relative">
        
        {/* Header Block */}
        <div className="text-center mb-8">
          <h1 className="text-4xl font-black bg-gradient-to-r from-purple-950 to-indigo-950 bg-clip-text text-transparent">
            Before & After Makeover
          </h1>
          <p className="text-sm font-semibold text-slate-600 mt-1">
            Slide to see the amazing transformation generated by Groq Vision & AI.
          </p>
        </div>

        {/* Dynamic Split-Image Slider Canvas */}
        <div className="bg-white/30 backdrop-blur-xl border border-white/40 p-6 rounded-[2.5rem] shadow-2xl space-y-6">
          <div 
            className="relative h-[450px] rounded-[1.8rem] overflow-hidden select-none shadow-inner group"
            onMouseMove={(e) => {
              if (e.buttons === 1 || e.touches) { 
                const rect = e.currentTarget.getBoundingClientRect();
                const x = ((e.clientX - rect.left) / rect.width) * 100;
                if (x >= 0 && x <= 100) setSliderPosition(x);
              }
            }}
          >
            {/* AFTER IMAGE layer (Base) */}
            <img 
              src="https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=1200" 
              alt="After Redesign" 
              className="absolute inset-0 w-full h-full object-cover pointer-events-none"
            />
            <span className="absolute bottom-4 right-4 bg-purple-950/80 backdrop-blur-md text-white text-[10px] font-black uppercase tracking-widest px-3 py-1.5 rounded-xl border border-white/10 z-10">
              After Redesign
            </span>

            {/* BEFORE IMAGE layer (Clip path wrapper) */}
            <div 
              className="absolute inset-0 w-full h-full overflow-hidden pointer-events-none"
              style={{ clipPath: `polygon(0 0, ${sliderPosition}% 0, ${sliderPosition}% 100%, 0 100%)` }}
            >
              <img 
                src="https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=1200" 
                alt="Original Space" 
                className="absolute inset-0 w-full h-[450px] object-cover max-w-none"
                style={{ width: '100%' }}
              />
            </div>
            <span 
              className="absolute bottom-4 left-4 bg-slate-950/80 backdrop-blur-md text-white text-[10px] font-black uppercase tracking-widest px-3 py-1.5 rounded-xl border border-white/10 z-10 transition-opacity"
              style={{ opacity: sliderPosition > 15 ? 1 : 0 }}
            >
              Original Space
            </span>

            {/* Interactive Slider Handle Bar */}
            <div 
              className="absolute top-0 bottom-0 w-1 bg-white cursor-ew-resize z-20 shadow-xl"
              style={{ left: `${sliderPosition}%` }}
            >
              <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-8 h-8 rounded-full bg-white text-purple-950 shadow-2xl border border-purple-200 flex items-center justify-center font-bold text-xs">
                ↔
              </div>
            </div>
          </div>

          {/* Project Summary Controls Block */}
          <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4 pt-2">
            <div>
              <h2 className="text-2xl font-black text-purple-950">{projectDetails.title}</h2>
              <p className="text-xs font-black text-purple-600 uppercase tracking-widest mt-0.5">
                Style Preference: {projectDetails.style}
              </p>
            </div>
            <button
              onClick={() => setIsModalOpen(true)}
              className="w-full md:w-auto bg-gradient-to-r from-purple-600 via-indigo-600 to-blue-600 text-white font-black px-6 py-4 rounded-xl shadow-lg hover:opacity-95 active:scale-95 transition-all text-xs uppercase tracking-wider"
            >
              View Complete Project Details
            </button>
          </div>
        </div>

        {/* ================= HIGH-FIDELITY GLASSMORPHIC PROJECT DETAILS MODAL ================= */}
        {isModalOpen && (
          <div className="fixed inset-0 bg-purple-950/20 backdrop-blur-md flex items-center justify-center p-4 z-50 animate-fade-in">
            <div className="bg-white/70 backdrop-blur-2xl border border-white/60 w-full max-w-2xl p-8 rounded-[2.5rem] shadow-2xl relative max-h-[90vh] overflow-y-auto space-y-6">
              
              {/* Close Button Trigger */}
              <button 
                onClick={() => setIsModalOpen(false)}
                className="absolute top-6 right-6 w-8 h-8 rounded-full bg-purple-950/10 hover:bg-purple-950/20 text-purple-950 flex items-center justify-center font-black transition-colors"
              >
                ✕
              </button>

              <div className="border-b border-purple-950/10 pb-4">
                <span className="text-[10px] font-black text-purple-600 tracking-widest uppercase">
                  Telemetry Blueprint Record Log
                </span>
                <h3 className="text-3xl font-black text-purple-950 mt-1">{projectDetails.title}</h3>
                <p className="text-xs font-semibold text-slate-500 mt-0.5">Compiled: {projectDetails.date} | Aesthetic: {projectDetails.style}</p>
              </div>

              {/* Analysis Log */}
              <div className="space-y-2">
                <h4 className="text-xs font-black text-purple-950 uppercase tracking-wider">Spatial Overview</h4>
                <p className="text-sm font-medium text-slate-700 leading-relaxed bg-white/40 p-4 rounded-xl border border-white/40 shadow-inner">
                  {projectDetails.analysis.overview}
                </p>
              </div>

              {/* Color Swatch Panel */}
              <div className="space-y-2">
                <h4 className="text-xs font-black text-purple-950 uppercase tracking-wider">Target Architectural Palette</h4>
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                  {projectDetails.analysis.palette.map((color, idx) => (
                    <div key={idx} className="bg-white/50 border border-white/50 p-2 rounded-xl flex flex-col items-center text-center shadow-sm">
                      <div 
                        className="w-full h-10 rounded-lg shadow-sm mb-1.5 border border-purple-950/5"
                        style={{ backgroundColor: color.split(" ")[0] }}
                      />
                      <span className="text-[10px] font-bold text-purple-950 leading-tight">{color}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Recommendations Checklists */}
              <div className="space-y-3">
                <h4 className="text-xs font-black text-purple-950 uppercase tracking-wider">Llama 4 Structural Blueprint Modifications</h4>
                <ul className="space-y-2.5">
                  {projectDetails.analysis.recommendations.map((rec, idx) => (
                    <li key={idx} className="flex items-start gap-3 text-sm font-medium text-slate-800">
                      <span className="flex-shrink-0 w-5 h-5 rounded-md bg-purple-950 text-white font-black text-[10px] flex items-center justify-center mt-0.5 shadow-sm">
                        {idx + 1}
                      </span>
                      <p className="leading-normal">{rec}</p>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Quick Close Button */}
              <button
                onClick={() => setIsModalOpen(false)}
                className="w-full bg-purple-950 text-white font-black py-3.5 rounded-xl shadow-md hover:opacity-90 active:scale-[0.99] transition-all text-xs uppercase tracking-wider"
              >
                Close Blueprint Portal
              </button>

            </div>
          </div>
        )}

      </div>
    </DashboardLayout>
  );
}